version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp_production
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
